version: '3.1'

services:
  postgres-order:
    image: postgres
    container_name: postgres-order
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./.data/postgres-order:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always
    networks:
      - microservices

  postgres-inventory:
    container_name: postgres-inventory
    image: postgres
    environment:
      POSTGRES_DB: inventory-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./.data/postgres-inventory:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - microservices

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    networks:
      - microservices

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

networks:
  microservices:
    driver: bridge